
.const {

    HLAadv	= 1
	
    guilddoor = 224    

		  tavern1 = 1
		  upstairsHallway2 = 2
		  villageStore3 = 3
		  smallRoom4 = 4
		  villagePath5 = 5
		  villageWell6 = 6
		  smallCathedral7 = 7
		  stoneAltar8 = 8
		  storageRoom9 = 9
		  guild10 = 10
		  townEntrance11 = 11
		  wellLitPath12 = 12
		  forestPath13 = 13
		  intersection14 = 14
		  redwoodForest15 = 15
		  oldOakTree16 = 16
		  atopForest17 = 17
		  grassRoomHut18 = 18
		  redwoodForest19 = 19
		  redwoodForest20 = 20
		  redwoodForest21 = 21
		  brokenPath22 = 22
		  brokenPath23 = 23
		  abandonedCottage24 = 24
		  byTheLake25 = 25
		  smallClearing26 = 26
		  grassyHillside27 = 27
		  onThePath28 = 28
		  windingRoad29 = 29
		  windingRoad30 = 30
		  junction31 = 31
		  woodenBridge32 = 32
		  bronzeStatue33 = 33
		  windingRoad34 = 34
		  purpleMountains35 = 35
		  purpleMountains36 = 36
		  purpleMountains37 = 37
		  purpleMountains38 = 38
		  darkCave39 = 39
		  purpleMountains40 = 40
		  purpleMountains41 = 41
		  onThePathSouth42 = 42
		  smallHillside43 = 43
		  grassySlopeDown44 = 44
		  decayingForest45 = 45
		  dyingForest46 = 46
		  withinDyingForest47 = 47
		  southernRoad48 = 48
		  grassyHillside49 = 49
		  southHillside50 = 50
		  easternPath51 = 51
		  dyingForest52 = 52
		  middleForest53 = 53
		  smallBridge54 = 54
		  southernSlope55 = 55
		  northernCell56 = 56
		  smallRavine57 = 57
		  endOfForest58 = 58
		  dyingForest59 = 59
		  dyingForest60 = 60
		  widePath61 = 61
		  smallCell62 = 62
		  darkenedDungeon63 = 63
		  smallCell64 = 64
		  endOfForest65 = 65
		  endOfForest66 = 66
		  castleMoat67 = 67
		  darkenedDungeon68 = 68
		  guestChambers69 = 69
		  mainHallway70 = 70
		  smallLibrary71 = 71
		  smallThrone72 = 72
		  twistedPassageway73 = 73
		  narrowTunnel74 = 74
		  twistedPassageway75 = 75
		  eastWestPassageway76 = 76
		  narrowOpening77 = 77
		  smallIntersection78 = 78
		  smallCrevice79 = 79
		  smallIntersection80 = 80
		  tinyFissure81 = 81
		  endOfTunnel82 = 82
		  tunnelJunction83 = 83
		  smallTunnel84 = 84
		  subterraneanPassageway85 = 85
		  easternJunction86 = 86
		  smallTunnel87 = 87
		  deadEnd88 = 88
		  twistingPassageway89 = 89
		  nearDeadEnd90 = 90
		  narrowPassageway91 = 91
		  narrowTunnel92 = 92
		  wideTunnel93 = 93
		  largeWaterfall94 = 94
		  smallKeep95 = 95
		  smallKeep96 = 96
		  redwoodForest97 = 97
		  redwoodForest98 = 98
		  redwoodForest99 = 99
		  narrowPath100 = 100
		  smallClearing101 = 101
		  redwoodForest102 = 102
		  dirtPath103 = 103
		  dirtPath104 = 104
		  smallKeep105 = 105
		  wellWornPath106 = 106
		  wellWornPath107 = 107
		  sandyBeach108 = 108
		  sandyBeach109 = 109
		  sandyBeach110 = 110
		  sandyBeach111 = 111
		  dirtPath112 = 112
		  sandyBeach113 = 113
		  sandyBeach114 = 114
		  sandyBeach115 = 115
		  sandyBeach116 = 116
		  sandyBeach117 = 117
		  sandyBeach118 = 118
		  sandyBeach119 = 119
		  sandyBeach120 = 120
		  easternCoastline121 = 121
		  eastOfSmallLagoon122 = 122
		  lighthouseAtFlora123 = 123
		  forestWoodlands124 = 124
		  forestWoodlands125 = 125
		  forestWoodlands126 = 126
		  middleWoodlands127 = 127
		  forestWoodlands128 = 128
		  forestWoodlands129 = 129
		  forestWoodlands130 = 130
		  forestWoodlands131 = 131
		  forestWoodlands132 = 132
		  forestWoodlands133 = 133
		  forestWoodlands134 = 134
		  topOfLighthouse135 = 135
		  insideLighthouse136 = 136
		  insideLighthouse137 = 137
		  onThePath138 = 138
		  onThePath139 = 139
		  forestJunction140 = 140
		  intersection141 = 141
		  spruceWoodland142 = 142
		  spruceWoodland143 = 143
		  widePath144 = 144
		  endPath145 = 145
		  forestWoodland146 = 146
		  forestWoodland147 = 147
		  forestWoodland148 = 148
		  forestWoodland149 = 149
		  smallClearing150 = 150
		  frontOfMansion151 = 151
		  smallBedroom152 = 152
		  mainHallway153 = 153
		  masterBedroom154 = 154
		  alongACorridor155 = 155
		  stoneArchway156 = 156
		  middleCorridor157 = 157
		  inTheKitchen158 = 158
		  guestBathroom159 = 159
		  smallBedroom160 = 160
		  livingRoom161 = 161
		  pantry162 = 162
		  smallToolshed163 = 163
		  smallGarden164 = 164
		  outdoorPatio165 = 165
		  lawn166 = 166
		  stoneFountain167 = 167
		  smallGarden168 = 168
		  lawn169 = 169
		  lawn170 = 170
		  oliveTree171 = 171
		  shindenVilla172 = 172
		  narrowBridge173 = 173
		  narrowBridge174 = 174
		  shallowPond175 = 175
		  westernPortico176 = 176
		  shallowPond177 = 177
		  shallowPond178 = 178
		  narrowBridge179 = 179
		  shallowPond180 = 180
		  shallowPond181 = 181
		  shallowPond182 = 182
		  grassySection183 = 183
		  eastOfVilla184 = 184
		  easternPortico185 = 185
		  easternPortico186 = 186
		  easternPortico187 = 187
		  pond188 = 188
		  islandOverlook189 = 189
		  southernHall190 = 190
		  southernHall191 = 191
		  hallwayTurn192 = 192
		  insideShinden193 = 193
		  insideShinden194 = 194
		  smallRoom195 = 195
		  southernHall196 = 196
		  southernHall197 = 197
		  appleOrchard198 = 198
		  vastCavern199 = 199
		  twistingPassageway200 = 200
		  twistingPassageway201 = 201
		  narrowPassage202 = 202
		  smallTunnel203 = 203
		  smallKeep204 = 204
		  darkTunnel206 = 206
		  darkTunnel207 = 207
		  largeRock208 = 208
		  magicalPool209 = 209
		  smallWaterfall210 = 210
		  secretTunnel211 = 211
		  secretTunnel212 = 212
		  darkTunnel213 = 213
		  darkTunnel214 = 214
		  darkTunnel215 = 215
		  darkTunnel216 = 216
		  darkTunnel217 = 217
		  darkTunnel218 = 218
		  darkTunnel219 = 219
		  darkTunnel220 = 220
		  darkTunnel221 = 221
		  sacredKeep222 = 222
		  topAppleTree223 = 223
		  
		  // additions
		  dustypath		= 225
		  pathnorth		= 226
		  mistymtns100	= 227
		  mistymtns200	= 228
		  mistymtns201	= 229
		  mistymtns202	= 230
		  mistymtns300	= 231
		  mistymtnsend	= 232
		  ravine		= 233
		  mysticgorge	= 234
		  grassyvalley01= 235
		  cyprusvalley	= 236
		  mossypond		= 237
		  grassymeadow	= 238
		  grassymeadow2 = 239
		  largetree0	= 240
		  largetree1	= 241
		  largetree2	= 242
		  southernvalley= 243
		  southernvalley2 = 244
		  byboulder		= 245
		  mistymtns400	= 246
		  mistycave0	= 247
		  mistycave1	= 248
		  mistycave2	= 249
		  mistycave3	= 250
		  		  
	
	// agents	  

    paladin		= 1
    villager	= 2
    clerk		= 3
    wolf 		= 4
    warrior 	= 5
    spectre 	= 6
    goblin 		= 7
    elf 		= 8
    hobbit 		= 9
    skeleton	= 10
    vampire 	= 11
    sorcerer 	= 12
    dragon 		= 13
    knight 		= 14
    barbarian 	= 15
    bear 		= 16
    kingcrab 	= 17
    crab 		= 18
    thief 		= 19
    werewolf 	= 20
    butler 		= 21
    eddie 		= 22
    bum 		= 23
    demigorgon 	= 24
    kukai 		= 25
    hellhound 	= 26
    ghoul 		= 27
    valkyrie 	= 28
    lich 		= 29
    tursk 		= 30
    wannabee 	= 31
    wisp		= 32
	monk		= 33
	
	
	unicorn	= 34
	eagle 	= 35
	goat	= 36
    golem	= 37
    kobold	= 38


	// objects
	
    bulletin    = 1
    guildkey    = 2
    flute       = 3
    lantern     = 4
    food        = 5
    rations     = 6
    oil         = 7
    sword       = 8
    cleaver     = 9
    rope        = 10
    currency    = 11
    broadsword = 12
    gauntlets = 13
    axe = 14
    helmet = 15
    cloak = 16
    ring = 17
    scimitar = 18
    armor = 19
    shield = 20
    longsword = 21
    bottle = 22
    dagger = 23
    battleaxe = 24
    apple = 25

    shroud = 27
    buckler = 28
    boomerang = 29
    horn	= 30
	firewhip	= 31
	anklet	= 32
	portals	= 33
}

.global {

	kukai_house	= 0
	lantern_quest = 0
	cavern_quest = 0
	castle_quest = 0
	sorcerer_quest = 0
	mansion_quest = 0
	werewolf_quest = 0
	vampire_quest = 0
	dragon_quest = 0
	
	temp_var	= 0
}

.defineobjects {

	.object: bulletin, "Bulletin Board" {
		.desc:
"
Quest#         Description                  Reward

1. Lantern    Find a missing lantern      100 gold
2. Goblin     Defeat an evil goblin       250 gold
3. Castle     Can you find the castle?    300 gold
4. Sorcerer   Find/dispatch the sorcerer  325 gold
5. Mansion    Explore a hidden mansion    ???
6. Werewolf   Befriend a lone werewolf    ???
7. Vampire    Vanquish the evil vampire   ???
8. Cavern     Defeat the evil guardian    ???
9. Dragon     This is the main quest      ???"

		.attributes [ @read ]
	}
	
	.object: guildkey, "key" {
		.desc: "A small wooden key."
		.attributes [ @get | @drop | @examine ]
	}
	
	.object: flute, "flute"	{
		.desc: "A small wooden flute"
		.attributes [ @get | @drop | @use | @examine ]
		.event: fluteEvent
	}
	
	.object: lantern, "lantern" {
		.desc: "A brass lantern with rusted hinges."
		.attributes [ @general ]
		.event: lanternQuest
	}
	
	.object: food, "food" {
		.desc: "These are standard food rations, lasting two weeks."
		.attributes [ @general ]
		.event: feedwerewolfEvent
	}
	
	.object: boomerang, "boomerang" {
		.desc: "A small wooden boomerang. It is slightly curved."
		.attributes [@general]
	}
	
	.object: rations, "rations" {
		.desc: "These are standard iron rations (lasting two weeks)."
		.attributes [ @fooditem ]
            .stack: 12
            .event: foodevent
	}
	
	.object: oil, "oil" {
		.desc: "A flask of oil used with the lantern."
		.attributes [ @general]
		.value: 5
	}
	
	.object: portals, "Portal" {
		.desc: "This is a portal between dimensions.  Where it leads is unknown"
		.attributes [@use | @examine ]
		.event: portalEvent
	}
	
	.wieldable: sword, "sword" {
		.desc: "A small metal sword with a diamond hilt."
		.attributes [@weaponitem]
		.value: 60
		.damage [ 1, 6 ]
		.hand: either
	}
	
	.wieldable: cleaver, "cleaver" {
		.desc: "A dull meat cleaver, unevenly sharpened."
		.attributes [@weaponitem]
		.value: 150
		.hand: either
		.damage [ 1, 3 ]
	}
	
	.object: rope, "rope" {
		.desc: "A coil of rope about 20' long."
		.attributes [@general]
		.event: ropeEvent
	}
	
	.object: currency, "Gold" {
		.desc: "Legal tender"
		.attributes [ @get | @examine ]
		.stack: @unlimited
	}

	.wieldable: broadsword, "broadsword"	{
		.desc: "A long metal broadsword with a sapphire hilt.  He who lives by the sword, dies by the sword."
		.attributes [@weaponitem]
		.value: 60
		.hand: primary
		.damage [2,8]
	}

	.wearable: gauntlets, "gauntlets"	{
		.desc: "A pair of full metal gauntlets."
		.attributes [@wearable]
		.value: 300
		.ac: 1
	}
	
	.wearable: anklet, "anklet" {
		.desc: "A glistening anklet worn around the ankles. Offers good protection."
		.attributes [@wearable]
		.ac: 1
	}

	.wieldable: axe, "axe"	{
		.desc: "A sharp metal axe. It is dual bladed."
		.attributes [@weaponitem]
		.value: 60
		.hand: either
		.damage [ 2, 8 ]
	}

	.wearable: helmet, "helmet"	{
		.desc: "A sturdy brass helmet.  Not intended for professional sports use."
		.attributes [@wearable]
		.value: 300
		.ac: 2
		.physical: 1
	}

	.wearable: cloak, "cloak"	{
		.desc: "An elven cloak tied at the waist by a small rope."
		.attributes [@wearable]
		.value: 300
		.ac: 5
		.physical: 3
	}

	.wearable: ring, "ring"	{
		.desc: "A magical ring of protection. It glows with a soft hue."
		.attributes [@wearable]
		.value: 300
		.physical: 1
	}

	.wieldable: scimitar, "scimitar"	{
		.desc: "A gleaming metal scimitar. It looks deadly."
		.attributes [@weaponitem]
		.value: 300
		.hand: primary	
	}

	.wearable: armor, "armor"	{
		.desc: "A fine suit of chain-linked armor."
		.attributes [@wearable]
		.value: 300
		.ac: 10
		.physical: 10
	}

	.wieldable: shield, "shield"	{
		.desc: "A crusader shield stained with blood."
		.attributes [@weaponitem]
		.value: 100
		.ac: 5
		.hand: secondary
	}

	.wieldable: longsword, "longsword"	{
		.desc: "A metal longsword with a ruby hilt."
		.attributes [@weaponitem]
		.value: 60
		.hand: primary
		.damage [2, 8]
	}

	.object: bottle, "bottle"	{
		.desc: "A smokey glass bottle."
		.attributes [ @get | @drop | @use | @examine ]
	}

	.wieldable: dagger, "dagger"	{
		.desc: "A small metal dagger with a jeweled hilt."
		.attributes [@weaponitem]
		.value: 10
		.hand: either
		.damage [ 1, 6 ]
	}

	.wieldable: battleaxe, "battleaxe"	{
		.desc: "A sturdy metal battleaxe. It looks sharp and lethal!  Caution, may cause injury or death if misused."
		.attributes [@weaponitem]
		.value: 60
		.hand: both
		.damage [4, 12]
	}

	.wieldable: firewhip, "firewhip" {
		.desc: "A flaming whip with a magical aura about it. It looks deadly!"
		.attributes [@weaponitem]
		.value: 600
		.hand: primary
		.damage [5, 15]
	}
	
	.object: apple, "apple"	{
		.desc: "A small red apple. It looks slightly rotten."
		.attributes [ @get | @drop | @use | @examine ]
	}

	.wearable: shroud, "shroud"	{
		.desc: "This is the holy shroud of Saint Nepan, an ancient cleric of the temple."
		.attributes [ @wearable]
	}

	.wieldable: buckler, "buckler"	{
		.desc: "A wooden buckler. Useful as a shield."
		.attributes [@weaponitem]
		.value: 100
		.ac: 5
		.hand: secondary
	}
	
	.object: horn, "horn" {
		.desc: "This is the magical horn of Galius. You can use it to disrupt magic."
		.attributes [@general]
		.event: hornEvent
	}

}

.defineagents {
	
	// the Paladin guards the guild.
	// he is too tough for the PC to defeat in combat! 
	.monster: paladin, "Paladin" {
		.desc: "A strong paladin wearing a metal pendant.  He seems of noble blood"
		.level: 8
		.attributes [ @examine | @talk | @attack ]
		.temperment: neutral
		.experience: 80
		.attack {
			.desc: "Slashes with Scimitar"
			.skill: 80
			.damage [ 2, 8 ]
		}
		.armor {
			.ac: 15
			.physical: 10
		}
		.event: paladinEvent
	}
	
	.monster: villager, "Villager" {
		.desc: "A common villager. He smiles at you briefly before passing."
		.level: 3
		.attributes [ @examine | @talk | @attack ]
		.event: talkEvents
		.temperment: neutral
		.experience: 30
		.attack {
			.skill: 30
			.damage [ 2, 6 ]
		}
	}
	
	.monster: clerk, "Clerk" {
		.desc: "A stout clerk. He looks well fed."
		.attributes [ @examine | @talk ]
		.event: talkEvents
	}

	.monster: wolf, "Wolf" {
		.desc: "A friendly wolf with yellow eyes. He seems content on watching you."
		.level: 2
		.attributes [ @examine | @talk | @attack ]
		.event: talkEvents
		.temperment: neutral
		.experience: 20
		.attack {
			.skill: 30
			.damage [ 1, 6 ]
		}
	}

	.monster: warrior, "Warrior" {
		.desc: "A warrior with flowing hair and a trim beard. He looks mean."
		.level: 4
		.attributes [ @examine | @talk | @attack ]
		.temperment: neutral
		.experience: 40
		.attack {
			.desc: "Slashes with Broadsword"
			.skill: 40
			.damage [ 2, 8 ]
		}
		.armor {
			.ac: 1
			.physical: 1
		}
		.event: warriorEvent
	}

	.monster: spectre, "Ghost" {
		.desc: "A translucent spectre. It haunts the surrounding forest."
		.level: 3
		.experience: 30
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 30
			.damage [3, 8]
		}
		.armor {
			.ac: 5
			.physical: 1
		}
	}

	.monster: goblin, "Goblin" {
		.desc: "An ugly goblin with brown teeth. He looks vicious and cunning."
		.level: 2
		.attributes [ @examine | @talk | @attack ]
		.temperment: neutral
		.experience: 20
		.attack {
			.skill: 20
			.damage [ 1, 6 ]
		}
		.event: goblinEvent
	}
	
	.monster: kobold, "Kobold" {
		.desc: "An evil kobold. It guards a sacred treasure, or so legend has it."
		.level: 4
		.attributes [ @examine | @talk | @attack ]
		.temperment: neutral
		.experience: 40
		.attack {
			.skill: 33
			.damage [ 3, 10 ]
		}
		.armor {
			.ac: 3
			.physical: 2
		}
		.event: koboldEvent
	}

	.monster: elf, "Elf" {
		.desc: "An elf of the surrounding forest. He seems peaceful."
		.level: 5
		.experience: 50
		.attributes [@examine | @talk | @attack ]
		.event: elfEvent
		.attack {
			.skill: 50
			.damage [1, 12]
		}
		.armor {
			.ac: 5			// cloak
			.physical: 4	// cloak + ring
		}
	}

	.monster: hobbit, "Hobbit" {
		.desc: "A small hobbit with furry feet."
		.level: 1
		.experience: 10
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 25
			.damage [1, 5]
		}
	}

	.monster: skeleton, "Skeleton" {
		.desc: "An undead skeleton. He is covered with blood and rotting flesh."
		.level: 4
		.attributes [@examine | @talk | @attack ]
		.event: skeletonEvent
		.experience: 40
		.attack {
			.desc: "Swings longsword"
			.skill: 40
			.damage [ 2, 8]
		}
		.armor {
			.ac: 5
			.physical: 5
		}
	}

	.monster: vampire, "Vampire" {
		.desc: "An evil vampire. He sucks the blood of unwitting victims."
		.level: 7
		.attributes [@examine | @talk | @attack ]
		.event: vampireEvent
		.experience: 70
		.attack {
			.skill: 70
			.damage [3, 10]
		}
		.armor {
			.ac: 10
			.physical: 5
		}
	}

	.monster: sorcerer, "Sorcerer" {
		.desc: "Once honorable, this sorcerer has turned to the arts of black magic."
		.attributes [@examine | @talk | @attack ]
		.event: sorcererEvent
		.level: 5
		.attributes [@examine | @talk | @attack ]
		.attack {
			.desc: "Zaps with wand"
			.skill: 50
			.damage [3, 10]
		}
		.armor {
			.ac: 10
			.physical: 5
		}
		.experience: 50
	}

	.monster: dragon, "Dragon" {
		.desc: "A large dragon with tough scales and powerful claws."
		.level: 12
		.experience: 1000
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.desc: "Breathes Fire"
			.skill: 120
			.damage [ 3, 24 ]
		}
		.armor {
			.ac: 10
			.physical: 5
		}
		.event: dragonEvent
	}

	.monster: knight, "Knight" {
		.desc: "An unholy knight, he serves only those with impure hearts."
		.level: 5
		.experience: 40
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 50
			.damage [4, 8]
		}
		.armor {
			.ac: 10
			.physical: 3
		}
	}

	.monster: barbarian, "Barbarian" {
		.desc: "A savage barbarian. He craves destruction and greed."
		.level: 4
		.experience: 40
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 40
			.damage [1, 12]
		}
		.armor {
			.ac: 10
			.physical: 3
		}
	}

	.monster: bear, "Bear" {
		.desc: "A large grizzly bear. It looks dangerous."
		.level: 2
		.experience: 20
		.attributes [@examine | @talk | @attack ]
		.attack {
			.desc: "Mauls"
			.skill: 20
			.damage [2, 8]
		}
	}

	.monster: kingcrab, "Kingcrab" {
		.desc: "This is a large kingcrab. It has claws and several legs."
		.level: 2
		.experience: 20
		.attributes [@examine | @attack ]
		.attack {
			.skill: 20
			.damage [1, 5]
		}
		.armor {
			.ac: 0
			.physical: 3
		}
	}

	.monster: crab, "Crab" {
		.desc: "This is a small crab. It has claws and several legs."
		.level: 1
		.experience: 10
		.attributes [@examine | @attack ]
		.attack {
			.skill: 10
			.damage [1, 5]
		}
		.armor {
			.ac: 0
			.physical: 2
		}
	}

	.monster: thief, "Thief" {
		.desc: "A no-good thief."
		.level: 2
		.experience: 20
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 20
			.damage [2, 6]
		}
		.armor {
			.ac: 5		// dexterous theif
		}
	}

	.monster: werewolf, "Werewolf" {
		.desc: "This vicious werewolf eyes you with a deadly gaze."
		.level: 3
		.attributes [@examine | @attack ]
		.experience: 30
		.attack {
			.skill: 30
			.damage [3, 8]
		}
		.armor {
			.ac: 0
			.physical: 3
		}
	}

	.monster: butler, "Butler" {
		.desc: "A tall butler. He looks old and cranky."
		.level: 1
		.experience: 10
		.attributes [@examine | @talk | @attack ]
		.event: butlerEvent
		.attack {
			.skill: 10
			.damage [1, 3]
		}
	}

	.monster: eddie, "Eddie" {
		.desc: "This is Eddie. He managed to get up here (somehow...)."
		.level: 1
		.experience: 10
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 10
			.damage [ 1, 3 ]
		}
	}

	.monster: bum, "Bum" {
		.desc: "A beach bum. He appears to be drinking something."
		.level: 1
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.experience: 10
		.attack {
			.skill: 10
			.damage [1, 3]
		}
	}

	.monster: demigorgon, "Demigorgon" {
		.desc: "This is an EVIL demigorgon! He has towering wings and strong claws."
		.level: 5
		.attributes [@examine | @talk | @attack ]
		.experience: 50
		.attack {
			.skill: 50
			.damage [1, 6]
		}
		.armor {
			.ac: 10
		}
		.event: talkEvents
	}

	.monster: kukai, "Kukai" {
		.desc: "This is Kukai, founder of the Shinden Villa.  He smiles at you with wisdom."
		.level: 5
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.experience: 50
		.attack {
			.skill: 50
			.damage [1,6]
		}
	}

	.monster: hellhound, "Hellhound" {
		.desc: "A large hellhound with fiery eyes.  It guards the entrance to the caverns."
		.level: 4
		.attributes [@examine | @talk | @attack ]
		.temperment: neutral
		.experience: 40
		.attack {
			.desc: "Breaths Fire"
			.skill: 40
			.damage [ 2, 12 ]
		}
		.armor {
			.ac: 5
			.physical: 2
		}		
		.event: hellhoundEvent
	}

	.monster: ghoul, "Ghoul" {
		.desc: "This nearly invisible spectre guards the surrounding tomb."
		.level: 4
		.experience: 40
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.skill: 40
			.damage [2, 6]
		}
		.armor {
			.physical: 5
		}
	}

	.monster: valkyrie, "Valkyrie" {
		.desc: "A magical valkyrie with flowing red hair. It has an impish look to it."
		.level: 5
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.experience: 50
		.attack {
			.skill: 50
			.damage [3, 10]
		}
		.armor {
			.ac: 8
			.physical: 4
		}
	}

	.monster: lich, "Lich" {
		.desc: "A shadowy creature moving about the darkness. It looks like death."
		.level: 5
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.experience: 50
		.attack {
			.skill: 50
			.damage [3, 9]
		}
		.armor {
			.ac: 10
		}
	}

//	.monster: tursk, "Tursk" {
//		.desc: "This is Tursk, an adventurer from out of town. He might prove useful."
//		.health: 500
//		.attributes [@examine | @talk | @attack ]
//		.event: talkEvents
//	}

	.monster: wannabee, "Wannabee" {
		.desc: "This is a monster known as a 'wannabee'.  It flutters around like a normal bee, but is invincible to attacks and unable to damage the player.  The game will enter into an infinite loop if an unsuspecting player decides to attack it."
		.health: 4000
		.attributes [@examine | @talk | @attack ]
		.event: talkEvents
		.attack {
			.desc: "Talks incoherently"
			.skill: 1
			.damage [ 1, 1 ]
		}
		.armor {
			.ac: 0
			.physical: 100
		}
	}
	
	.monster: unicorn, "Unicorn" {
		.desc: "A magical unicorn with a large horn. It looks very majestic!"
		.level: 12
		.experience: 1000
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.skill: 120
			.damage [ 3, 24 ]
		}
		.armor {
			.ac: 10
		}
		.event: talkEvents
	}
	
	.monster: eagle, "Eagle" {
		.desc: "A bald eagle (quite rare in these parts). It has massive wings!"
		.level: 3
		.experience: 30
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.skill: 30
			.damage [ 1, 8 ]
		}
		.armor {
			.ac: 5
		}
		.event: talkEvents
	}
	
	.monster: goat, "goat" {
		.desc: "A small goat. It looks a bit lost."
		.level: 1
		.experience: 10
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.skill: 10
			.damage [ 1, 3 ]
		}
		.event: talkEvents
	}
	
	.monster: wisp, "wisp" {
		.desc: "A magical will o' the wisp. It flutters about, illuminating the darkness."
		.level: 4
		.experience: 40
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.skill: 40
			.damage [ 2, 6 ]
		}
		.event: wispEvent
	}
	
	.monster: golem, "golem" {
		.desc: "A giant stone golem. It looks massive enough to crush boulders!"
		.level: 5
		.experience: 50
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.desc: "Smashes"
			.skill: 50
			.damage [ 3, 18 ]
		}
		.armor {
			.physical: 5
		}
		.event: golemEvent
	}
	
	.monster: monk, "monk" {
		.desc: "A simple monk, pious and forthright. He seems very peaceful."
		.level: 2
		.experience: 20
		.attributes [ @examine | @talk | @attack ]
		.attack {
			.desc: "Punches"
			.skill: 20
			.damage [ 1, 6 ]
		}
		.event: talkEvents
	}
}	

.defineplayer: "Seti" {
	.level: 1
//	.health: 200
//	.special [10, 10, 10, 10, 10, 10, 10 ]
	.special [6, 5, 6, 7, 6, 6, 4 ]
}
